version: '3'
services:
  db:
    build: .
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: app
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    build:
      context: .
      dockerfile: adminer.dockerfile
    ports:
      - "8080:8080"

  webserver:
    build: ./docker
    ports:
      - "9000:9000"
    volumes:
      - front:/var/www/html

volumes:
  pg-data:
  front:


